export const shahadaLanguages = {
  options: [
    {
      shahada: [
        "أشهد",
        "ألا",
        "إله",
        "إلا",
        "الله",
        "وأشهد",
        "أن",
        "محمدا",
        "رسول",
        "الله",
      ],
      congrats: "أحسنت",
      label: "Arabic",
      code: "ar",
    },
    {
      shahada: [
        "I bear witness",
        "That",
        "There is no god",
        "But Allah",
        "And",
        "I bear witness",
        "That",
        "Muhammad is",
        "The Messenger",
        "Of God",
      ],
      first_part: "I bear witness that there is no god but Allah",
      second_part: "And I bear witness that Muhammad is the Messenger of God",
      congrats: "good",
      label: "English",
      code: "en",
    },
  ],
  // latin: [
  //   "ašhadu",
  //   "ʾan lā ʾilāha",
  //   "ʾilla -llāhu,",
  //   "wa-ʾašhadu ʾ",
  //   " ʾanna muḥammadan",
  //   "rasūlu -llāh",
  // ],
};
